{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "590a3ae2-2300-45b7-a222-eb1cfd455fda",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting app.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile app.py\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import seaborn as sns               # For enhanced plots\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_squared_error, r2_score\n",
    "\n",
    "# Load dataset\n",
    "df = pd.read_csv(\"StudentPerformanceFactors.csv\")\n",
    "\n",
    "# Page config\n",
    "st.set_page_config(\n",
    "    page_title=\"Student Performance Predictor\",\n",
    "    page_icon=\"📚\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Sidebar Branding\n",
    "st.sidebar.title(\"EduAnalytics\")\n",
    "st.sidebar.markdown(\"Smart Student Performance Prediction Platform\")\n",
    "\n",
    "# Sidebar Navigation\n",
    "page = st.sidebar.selectbox(\"Navigation\", [\n",
    "    \"Home\",\n",
    "    \"About\",\n",
    "    \"Dataset Insights\",\n",
    "    \"Exploratory Analysis\",\n",
    "    \"Predictive Model Performance\",\n",
    "    \"Exam Score Estimation\"\n",
    "])\n",
    "\n",
    "# HOME PAGE\n",
    "if page == \"Home\":\n",
    "    st.markdown(\"<h1 style='text-align: center; color: black; font-size: 48px; font-weight: bold;'>Welcome to EduAnalytics</h1>\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='text-align: center; font-size: 20px;'>\n",
    "        This platform uses real-world data and machine learning to predict student exam performance based on study habits, attendance, motivation, and more.  \n",
    "        Explore insights, train models, and make informed predictions — all in one interactive dashboard.\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ABOUT PAGE\n",
    "elif page == \"About\":\n",
    "    st.markdown(\"<h2 style='text-align: center; color: black; font-size: 36px; font-weight: bold;'>About EduAnalytics</h2>\", unsafe_allow_html=True)\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    <div style='text-align: center; font-size: 18px;'>\n",
    "        This app helps predict student exam scores using data like study hours, attendance, and motivation.  \n",
    "        It guides you through exploring the data, building a model, checking its accuracy, and making predictions — all in one easy-to-use dashboard.\n",
    "    </div>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "    \n",
    "# DATASET INSIGHTS\n",
    "elif page == \"Dataset Insights\":\n",
    "    import seaborn as sns\n",
    "\n",
    "    st.markdown(\"<h2 style='text-align: center; color: black; font-size: 32px; font-weight: bold;'>Dataset Insights</h2>\", unsafe_allow_html=True)\n",
    "    # 🔹 First 20 Records\n",
    "    st.subheader(\" First 20 Records\")\n",
    "    st.dataframe(df.head(20))\n",
    "\n",
    "    # 🔹 Summary Statistics\n",
    "    st.subheader(\" Summary Statistics\")\n",
    "    st.write(df.describe())\n",
    "\n",
    "\n",
    "    # 🔹 Grouped Stats: Motivation Level\n",
    "    st.subheader(\" Average Exam Score by Motivation Level\")\n",
    "    avg_motivation = df.groupby(\"Motivation_Level\")[\"Exam_Score\"].mean().reset_index()\n",
    "    st.dataframe(avg_motivation)\n",
    "\n",
    "    fig1, ax1 = plt.subplots()\n",
    "    sns.barplot(x=\"Motivation_Level\", y=\"Exam_Score\", data=df, ax=ax1, palette=\"Blues\")\n",
    "    ax1.set_title(\"Average Exam Score by Motivation Level\")\n",
    "    ax1.set_xlabel(\"Motivation Level\")\n",
    "    ax1.set_ylabel(\"Average Exam Score\")\n",
    "    st.pyplot(fig1)\n",
    "\n",
    "    # 🔹 Grouped Stats: School Type (if available)\n",
    "    if \"School_Type\" in df.columns:\n",
    "        st.subheader(\" Average Exam Score by School Type\")\n",
    "        avg_school = df.groupby(\"School_Type\")[\"Exam_Score\"].mean().reset_index()\n",
    "        st.dataframe(avg_school)\n",
    "\n",
    "        fig2, ax2 = plt.subplots()\n",
    "        sns.barplot(x=\"School_Type\", y=\"Exam_Score\", data=df, ax=ax2, palette=\"Greens\")\n",
    "        ax2.set_title(\"Average Exam Score by School Type\")\n",
    "        ax2.set_xlabel(\"School Type\")\n",
    "        ax2.set_ylabel(\"Average Exam Score\")\n",
    "        st.pyplot(fig2)\n",
    "\n",
    "# EXPLORATORY ANALYSIS\n",
    "elif page == \"Exploratory Analysis\":\n",
    "    import seaborn as sns\n",
    "\n",
    "    st.markdown(\"<h2 style='text-align: center; color: black; font-size: 32px; font-weight: bold;'>Exploratory Analysis: Key Questions</h2>\", unsafe_allow_html=True)\n",
    "    # Question 1\n",
    "    st.markdown(\" **1. Does studying more hours improve exam scores?**\")\n",
    "    fig1, ax1 = plt.subplots()\n",
    "    sns.regplot(x=df[\"Hours_Studied\"], y=df[\"Exam_Score\"], ax=ax1,\n",
    "                scatter_kws={\"alpha\":0.5}, line_kws={\"color\":\"red\"})\n",
    "    ax1.set_title(\"Hours Studied vs Exam Score\")\n",
    "    ax1.set_xlabel(\"Hours Studied\")\n",
    "    ax1.set_ylabel(\"Exam Score\")\n",
    "    st.pyplot(fig1)\n",
    "    st.caption(\"Graph: Regression plot showing correlation between study hours and exam scores.\")\n",
    "\n",
    "    # Question 2\n",
    "    st.markdown(\" **2. Does attendance percentage affect exam performance?**\")\n",
    "    fig2, ax2 = plt.subplots()\n",
    "    sns.regplot(x=df[\"Attendance\"], y=df[\"Exam_Score\"], ax=ax2,\n",
    "                scatter_kws={\"alpha\":0.5}, line_kws={\"color\":\"green\"})\n",
    "    ax2.set_title(\"Attendance vs Exam Score\")\n",
    "    ax2.set_xlabel(\"Attendance (%)\")\n",
    "    ax2.set_ylabel(\"Exam Score\")\n",
    "    st.pyplot(fig2)\n",
    "    st.caption(\"Graph: Regression plot showing impact of attendance on exam scores.\")\n",
    "\n",
    "    # Question 3\n",
    "    st.markdown(\" **3. Does sleep duration influence exam performance?**\")\n",
    "    fig3, ax3 = plt.subplots()\n",
    "    sns.regplot(x=df[\"Sleep_Hours\"], y=df[\"Exam_Score\"], ax=ax3,\n",
    "                scatter_kws={\"alpha\":0.5}, line_kws={\"color\":\"purple\"})\n",
    "    ax3.set_title(\"Sleep Hours vs Exam Score\")\n",
    "    ax3.set_xlabel(\"Sleep Hours\")\n",
    "    ax3.set_ylabel(\"Exam Score\")\n",
    "    st.pyplot(fig3)\n",
    "    st.caption(\"Graph: Regression plot showing relationship between sleep and performance.\")\n",
    "\n",
    "    # Optional: Correlation Matrix\n",
    "    st.markdown(\" **4. Overall correlation between numeric features**\")\n",
    "    numeric_cols = df.select_dtypes(include=np.number).columns\n",
    "    corr = df[numeric_cols].corr()\n",
    "    fig4, ax4 = plt.subplots(figsize=(8,6))\n",
    "    im = ax4.imshow(corr, cmap=\"Blues\")\n",
    "    ax4.set_xticks(range(len(numeric_cols)))\n",
    "    ax4.set_yticks(range(len(numeric_cols)))\n",
    "    ax4.set_xticklabels(numeric_cols, rotation=90)\n",
    "    ax4.set_yticklabels(numeric_cols)\n",
    "    fig4.colorbar(im, ax=ax4)\n",
    "    ax4.set_title(\"Correlation Matrix\")\n",
    "    fig4.tight_layout()\n",
    "    st.pyplot(fig4)\n",
    "    st.caption(\"Graph: Heatmap showing correlations among numeric features.\")\n",
    "# PREDICTIVE MODEL PERFORMANCE\n",
    "elif page == \"Predictive Model Performance\":\n",
    "    st.markdown(\"<h2 style='text-align: center; color: black; font-size: 32px; font-weight: bold;'>Train & Evaluate Model</h2>\", unsafe_allow_html=True)\n",
    "\n",
    "    X = df[[\"Hours_Studied\"]]\n",
    "    y = df[\"Exam_Score\"]\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "    model = LinearRegression()\n",
    "    model.fit(X_train, y_train)\n",
    "    y_pred = model.predict(X_test)\n",
    "    mse = mean_squared_error(y_test, y_pred)\n",
    "    rmse = np.sqrt(mse)\n",
    "    r2 = r2_score(y_test, y_pred)\n",
    "\n",
    "    st.subheader(\"Model Performance Metrics\")\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    col1.metric(\"RMSE\", f\"{rmse:.2f}\")\n",
    "    col2.metric(\"R² Score\", f\"{r2:.4f}\")\n",
    "    col3.metric(\"Intercept\", f\"{model.intercept_:.2f}\")\n",
    "    st.write(\"Slope:\", model.coef_[0])\n",
    "    st.success(\"Model trained successfully!\")\n",
    "\n",
    "# EXAM SCORE ESTIMATION\n",
    "elif page == \"Exam Score Estimation\":\n",
    "    st.markdown(\"<h2 style='text-align: center; color: black; font-size: 32px; font-weight: bold;'>Predict Exam Score</h2>\", unsafe_allow_html=True)\n",
    "    study_hours = st.number_input(\"Enter Hours Studied:\", min_value=0, max_value=12, value=5)\n",
    "\n",
    "    # Train model\n",
    "    X = df[[\"Hours_Studied\"]]\n",
    "    y = df[\"Exam_Score\"]\n",
    "    model = LinearRegression()\n",
    "    model.fit(X, y)\n",
    "\n",
    "    # Predict and display score\n",
    "    if st.button(\"Estimate Score\"):\n",
    "        new_data = pd.DataFrame({\"Hours_Studied\": [study_hours]})\n",
    "        score = model.predict(new_data)[0]\n",
    "        st.success(f\"Estimated Exam Score: {score:.2f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fb0a126-6a64-4fcc-940d-6f892af18a77",
   "metadata": {},
   "outputs": [],
   "source": [
    "!Streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c044d679-0abf-4824-a6c3-00811c19ac04",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
